on:
  workflow_call:
    inputs:
      skip-lint:
        required: false
        type: boolean
      skip-format:
        required: false
        type: boolean
jobs:
  validate:
    runs-on: ubuntu-24.04
    container:
      image: martoc/cloudformation-tools:0.2.65
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10
          fetch-tags: true
      - name: Lint
        if: ${{ !inputs.skip-lint }}
        run: |
          if [ -d src ]; then
            if [ -d src/cloudformation/ ]; then
              if [ "$(find src/cloudformation -maxdepth 1 -type f -name '*.yaml' -print -quit)" ]; then
                for FILE in src/cloudformation/*.yaml; do
                  cfn-lint $FILE
                done
              else
                echo "No Cloudformation templates found"
              fi
            else
              echo "No Cloudformation directory found"
            fi
          else
            echo "No source code found"
          fi
      - name: Check AWS Cloudformation template format
        if: ${{ !inputs.skip-format }}
        run: |
          if [ -d src ]; then
            if [ -d src/cloudformation/ ]; then
              if [ "$(find src/cloudformation -maxdepth 1 -type f -name '*.yaml' -print -quit)" ]; then
                for FILE in src/cloudformation/*.yaml; do
                  rain fmt --verify $FILE
                done
              else
                echo "No Cloudformation templates found"
              fi
            else
              echo "No Cloudformation directory found"
            fi
          else
            echo "No source code found"
          fi
  build:
    needs: [validate]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10
          fetch-tags: true
      - name: Tag
        uses: martoc/action-tag@v0
      - name: Release on GitHub
        uses: martoc/action-release@v0
        if: ${{ github.event_name != 'pull_request' }}
