on:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-22.04
    container:
      image: martoc/cloudformation-tools:0.1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10
          fetch-tags: true
      - name: Lint
        run: |
          cfn-lint src/cloudformation/*.yaml
      - name: Check AWS Cloudformation template format
        run: |
          for FILE in src/cloudformation/*.yaml; do
            rain fmt --verify $FILE
          done
  build:
    needs: [validate]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10
          fetch-tags: true
      - name: Tag
        uses: martoc/action-tag@v0
      - name: Release on GitHub
        uses: martoc/action-release@main
